on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/8ee1b5fa8ac778b08d3ecb2ed69666f1
          gist_title: 22-COMUNICACIONUART-CCS-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/Comunicación Serial.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/f5b0a02b20ead22fd92e3fa4d1bb78d2
          gist_title: 22-ComunnicaciónUART-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/Comunicación Serial.c
          file_encoding: WINDOWS-1252